Create database FMCG_projects

use FMCG_projects

select * from FMCG_Sales

select count(*) as Total_Rows from FMCG_sales

select Top 5 * from FMCG_sales


-- Business questions

--What is the total sales/revenue generated by the business?

select sum(revenue) as Total_sales from FMCG_sales 

--What is the total number of units sold by the business?

select sum(units) as Total_units_sold from FMCG_sales

--What is the total sales/revenue generated by each city?

select City, sum(revenue) as Total_sales from FMCG_sales group by City

--Which city generated the highest total revenue in 2024

select top 1 city, sum(revenue) as Total_revenue from FMCG_sales group by city order by sum(revenue) desc

--Which product category generated the highest total revenue?

select top 1 category, sum(revenue) as Total_revenue from FMCG_sales group by category order by sum(revenue) desc 

--Which brand generated the highest total revenue?

select top 1 Brand, sum(revenue) as Total_revenue from FMCG_sales group by brand order by sum(revenue)desc

--Which month generated the highest total revenue in 2024?

select top 1 Format(invoice_date,'MMMM') as Month, sum(revenue) as Total_revenue from FMCG_sales group by Format(invoice_date,'MMMM') order by sum(revenue) desc

--Which cities generated total revenue higher than the overall average revenue?

select city, sum(revenue) as Total_revenue from FMCG_sales group by city having sum(revenue) >(select avg(revenue) from FMCG_sales)

--Which product categories generated more than ₹49,00,000 in total revenue?

select category, sum(revenue) as Total_revenue from FMCG_sales group by category having sum(revenue) > 4900000

--Rank the brands based on their total revenue, from highest to lowest.

select Brand, sum(revenue) as Total_revenue, rank() over (order by sum(revenue) desc) as Rank from FMCG_sales group by Brand

--Within each product category, rank the brands based on their total revenue from highest to lowest.

select category, Brand, sum(revenue) as Total_revenue, rank() over (partition by Category order by sum(revenue) desc) as Rank from FMCG_sales group by Category,Brand

--Calculate the month-over-month (MoM) change in total revenue for each month of 2024.

with Monthly_revenue as 
(
select month(invoice_date) as Month_Number, Format(invoice_date,'MMMM') as Month_name, sum(revenue) as Total_revenue from fmcg_sales
group by month(invoice_date), format(invoice_date,'MMMM')
)
select month_name, Total_revenue, Lag(Total_revenue) over (order by Month_number) as Previous_Month_Revenue,
Total_revenue- Lag(Total_revenue) over (order by month_number) as MOM_change
from Monthly_Revenue order by Month_number


--Calculate the total revenue generated from Loyalty Customers and Non-Loyalty Customers separately.

select 
case when Loyalty_flag = 1 then 'Loyalty Customer' else 'Non Loyalty Customer'
end as customer_type, sum(revenue) as Total_revenue from FMCG_sales group by case when Loyalty_flag = 1 then 'Loyalty Customer' else 'Non Loyalty Customer'
end 

--Calculate the total revenue generated through each sales channel, along with the percentage contribution of each channel to overall revenue.

select Channel, sum(revenue) as Total_revenue, sum(revenue)/(select sum(revenue) from Fmcg_sales) * 100 as PCT_contribution from fmcg_sales group by channel

--Identify the cities where the average Stock_On_Hand is greater then average Reorder_Level.

select city, avg(stock_on_hand) as Avg_stock_on_hand from fmcg_sales group by city having avg(stock_on_hand) > (select avg(reorder_level) from fmcg_sales)

--Calculate the average revenue per transaction for each month of 2024.

select Format(invoice_date,'MMMM') as Month, avg(Revenue) as Average_revenue from FMCG_Sales group by Format(invoice_date,'MMMM'),month(invoice_date) order by month(invoice_date)  

--Calculate the total number of transactions and total revenue for each customer loyalty group, and classify the groups as “Loyalty” and “Non-Loyalty”.

select case when Loyalty_flag = 1 then 'Loyalty' else 'Non Loyalty' end as Customer_Loyalty ,
count(invoice_date) as Total_Transactions, round(sum(revenue),2) as Total_revenue from fmcg_sales group by case when Loyalty_flag = 1 then 'Loyalty' else 'Non Loyalty' end

--Identify the top 2 brands in each city based on total revenue.

with Top_2 as
(
select city, brand, sum(revenue) as Total_revenue, rank() over(partition by city order by sum(revenue) desc) as Rank from fmcg_sales group by City,brand
)
select city, brand, round(Total_revenue,2) as Total_Revenue ,rank from Top_2 where rank <=2

--Calculate the percentage of total revenue contributed by each payment method.

select payment_mode, sum(revenue) as Total_revenue, round(sum(revenue)/(select sum(revenue) from fmcg_sales) * 100,2) as PCT from fmcg_sales group by payment_mode

-------------------------------------END-----------------------------------------------------


